### ISSUE TITLE
Personal version support? 

### ISSUE THREAD

**Issue by travistabbal** [thetazzbot/FreeExpression#6]
I recently was given a Personal model machine and would like to use Inkscape to control it. Freecut seems to be dead, and looked to use a custom command set anyway. The docs indicate that the hardware is mostly the same, so I thought I might ask about it. I expect I would need to disable any code for hardware my machine lacks, I just want to make sure that the cutting code is at least close to compatible.

**Comment by markawilliamson** [comment]
The original prject by arlet supports personal version. I may make an attempt to incorporate it but for now you can use his code but it's old and not updated anymore

**Comment by MrTev** [comment]
Gary hooked up another LCD module instead of using the OLED in the Cake Mini. Does the updated code use the original Cake OLED display? Also - I thought I had all the wires soldered correctly for JTAG but I can't read the device signature, erase the chip or program it. (It does read 4.9V from the board.) When programming the chip do I leave all the wire connectors plugged in? I assume at least the keypad harness needs plugged in so I can turn on the power to the board.

Thanks so much for the update.

**Comment by markawilliamson** [comment]
The first thing to do is use isp programmer to set the high.jtagen fuse.
Problem is with jtag enabled it disables the oled lol.

We can Skype sometime and I could help you get going.

Regards,

Mark
